version: '2.15.1'

services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "test_database"

  web:
    image: image1
    restart: always
    command: python /test_app/manage.py runserver 0.0.0.0:8000
    environment:
      DEBUG: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_database
    ports:
      - 8000:8000
    depends_on:
      - postgres
