version: '2.15.1'

services:
  db:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db

  web:
    build: .
    restart: always
    command: python /test_app/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/test_app/
    environment:
      DEBUG: 1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST: db
    ports:
      - 8000:8000
    depends_on:
      - db
volumes:
  postgres_data:
